---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
   image: "{{ ami }}"
   architecture: "workshop-ec2-healthchecks"
   loadb: "{{architecture}}-lb"
   auto_sc:  "{{architecture}}-asg"
   lc: "{{architecture}}-lc"

  vars_files:
    #contains the variables ami_access and ami_secret
    - amiKeys.yml
    #contains the variables keypair, group, subnetID and regi
    - regionInfo.yml

  tasks:
   #http://stackoverflow.com/questions/34016583/ansible-ec2-elb-lb-https-to-http-error
   #load balancer
   - ec2_elb_lb:
      aws_access_key: '{{ ami_access }}'
      aws_secret_key: '{{ ami_secret }}'
      security_group_ids: '{{group}}'
      name: "{{loadb}}"
      region: "{{regi}}"
      health_check:
        ping_protocol: http
        ping_port: 8080
        ping_path: "/health"
        response_timeout: 5
        interval: 60
        unhealthy_threshold: 2
        healthy_threshold: 2
      subnets: "{{ subnetID }}"
      state: present
      listeners:
       - protocol: http
         load_balancer_port: 80
         instance_port: 80

   #info on the ec2_lc module
   #http://docs.ansible.com/ansible/ec2_lc_module.html

   #ansible 2.0 required for this task, installation directions at
   #http://stackoverflow.com/questions/34903026/update-ansible-1-9-4-to-ansible-2-0
   #launch config
   - ec2_lc:
      aws_access_key: '{{ ami_access }}'
      aws_secret_key: '{{ ami_secret }}'
      region:  "{{regi}}"
      name: '{{lc}}'
      image_id: '{{ image }}'
      key_name: "{{ keypair }}"
      security_groups: '{{ group }}'
      instance_type: t2.micro
      volumes:
       - device_name: /dev/sda1
         volume_size: 100
         device_type: io1
         iops: 3000
         delete_on_termination: true
      user_data: "{{ bootstrap_content }}"

   #http://docs.ansible.com/ansible/ec2_asg_module.html
   #auto scaling group
   - ec2_asg:
      aws_access_key: '{{ ami_access }}'
      aws_secret_key: '{{ ami_secret }}'
      region:  "{{ regi }}"
      name: '{{ auto_sc }}'
      load_balancers: '{{ loadb }}'
      launch_config_name: '{{ lc }}'
      min_size: 2
      max_size: 4
      desired_capacity: 2
      vpc_zone_identifier: '{{ subnetID }}'
      wait_for_instances: true
      health_check_period: 300 #tune this value, currently takes too long
      health_check_type: ELB
      tags:
        - Team: idun
        # fix tags placeholder problem