---
- hosts: all
  serial: 1

  pre_tasks:
    - easy_install: name=pip state=latest
      become: yes
    - pip: name=docker-py
      become: yes

  tasks:
    - name: Provision app
      docker:
          docker_api_version: 1.21
          image: antonfenske/rest-webservice:{{ app_version }}
          name: rest
          state: reloaded
          ports:
          - '8080:8080'
      become: yes