---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
   image: "{{ ami }}"
   architecture: "workshop-basic"
   loadb: "{{architecture}}-lb"
   auto_sc:  "{{architecture}}_asg"
   lc: "{{architecture}}_lc"

  vars_files:
    - amiKeys.yml
    - regionInfo.yml

  tasks:
   - name: ELB
     ec2_elb_lb:
      aws_access_key: '{{ ami_access }}'
      aws_secret_key: '{{ ami_secret }}'
      security_group_ids: '{{group}}'
      name: "{{loadb}}"
      region: "{{regi}}"
      subnets: "{{ subnetID }}"
      state: "{{ state }}"
      listeners:
       - protocol: http
         load_balancer_port: 80
         instance_port: 80

   - name: Launch Configuration
     tags:
      - lc
     ec2_lc:
      aws_access_key: '{{ ami_access }}'
      aws_secret_key: '{{ ami_secret }}'
      region:  "{{regi}}"
      name: '{{lc}}'
      image_id: '{{ image }}'
      key_name: "{{ keypair }}"
      security_groups: '{{ group }}'
      instance_type: t2.micro
      volumes:
       - device_name: /dev/sda1
         volume_size: 100
         device_type: io1
         iops: 3000
         delete_on_termination: true
      user_data: "{{ bootstrap_content }}"
      state: "{{ state }}"

   - name: Auto-scaling group
     tags:
      - asg
     ec2_asg:
      aws_access_key: '{{ ami_access }}'
      aws_secret_key: '{{ ami_secret }}'
      region:  "{{ regi }}"
      name: '{{ auto_sc }}'
      load_balancers: '{{ loadb }}'
      launch_config_name: '{{ lc }}'
      min_size: 2
      max_size: 4
      desired_capacity: 2
      vpc_zone_identifier: '{{ subnetID }}'
      wait_for_instances: true
      tags: "{{ tags }}"
      state: "{{ state }}"